framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true
    trusted_hosts:  ['^todolist-oc-p8$']
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        #cookie_samesite: lax

    #esi: true
    fragments: ~
    php_errors:
        log: true
